[[headers]]
  for = "/*"
  [headers.values]
    # Content-Security-Policy = "default-src https: 'unsafe-inline'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
    
[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"